title: Minecraft Resource Packs
remote_theme: furglitch/furglitch.github.io
repository: furglitch/mc-resourcepack
logo: "https://raw.githubusercontent.com/Furglitch/furglitch.github.io/refs/heads/main/assets/images/custom/icons/furglitch_logo_square.svg"
favicon_ico: "https://raw.githubusercontent.com/Furglitch/furglitch.github.io/refs/heads/main/assets/images/custom/icons/furglitch_logo_square.ico"

baseurl: "mc-resourcepack"

nav_external_links:
  - title: " "
    hide_icon: true
  - title: "--- Other Projects ---"
    hide_icon: true
  - title: Mod Organizer 2 Linux Installer (MO2-LINT)
    url: https://wiki.furglitch.com/modorganizer2-linux-installer/
    hide_icon: true
  - title: Mod Organizer 2 Separator Generator
    url: https://wiki.furglitch.com/modorganizer2-separator-generator/
    hide_icon: true
  - title: Mod Organizer 2 NXM Collection Downloader
    url: https://wiki.furglitch.com/modorganizer2-nxm-collection-dl/
    hide_icon: true
  - title: "KenkuKraft: Infected"
    url: https://wiki.furglitch.com/kenkukraft/
    hide_icon: true
  - title: "Vending Block: Restocked"
    url: https://wiki.furglitch.com/vending-block-restocked/
    hide_icon: true
  - title: Docker Stack
    url: https://wiki.furglitch.com/docker-stack/
    hide_icon: true
  - title: Dotfiles
    url: https://wiki.furglitch.com/.dotfiles/
    hide_icon: true

plugins:
  - jekyll-remote-theme